### PR TITLE
Phpstan/lint

### PR DESCRIPTION
**Pull request by JaxkDev**
Linked to poggit/poggit#214

Adds PHPStan linting configuration. 
Also as discussed this also splits the linting options to configure some specific linting done by poggit.

### CODE REVIEW

**Comment by SOF3** [comment]
Did you forget a close brace?

**Comment by JaxkDev** [comment]
🤦‍♂️

**Comment by SOF3** [comment]
Does it still support the legacy `lint: false` syntax?
If it does, please use `boolean | {...}` instead of just `{...}`.

**Comment by JaxkDev** [comment]
It doesn’t, but if BC is wanted I could.

**Comment by JaxkDev** [comment]
Also should I just add a whole page for lint/phpstan there’s a bit to cover:
- Default Config.
- Default paths inside container (pmmp,dependancies).
- Composer support.

**Comment by SOF3** [comment]
I guess BC is better.

**Comment by SOF3** [comment]
> Also should I just add a whole page for lint/phpstan there’s a bit to cover:
> 
>     * Default Config.
> 
>     * Default paths inside container (pmmp,dependancies).
> 
>     * Composer support.

I don't think it is necessary to document default paths inside container. Why would we need to?

**Comment by JaxkDev** [comment]
> > Also should I just add a whole page for lint/phpstan there’s a bit to cover:
> 
> > 
> 
> >     * Default Config.
> 
> > 
> 
> >     * Default paths inside container (pmmp,dependancies).
> 
> > 
> 
> >     * Composer support.
> 
> 
> 
> I don't think it is necessary to document default paths inside container. Why would we need to?

So they can setup a correct phpstan config that points to the right places for things like dependency’s in /dep and plugin in /source

**Comment by SOF3** [comment]
> > > Also should I just add a whole page for lint/phpstan there’s a bit to cover:
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > * Default Config.
> > > ```
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > * Default paths inside container (pmmp,dependancies).
> > > ```
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > * Composer support.
> > > ```
> > 
> > 
> > I don't think it is necessary to document default paths inside container. Why would we need to?
> 
> So they can setup a correct phpstan config that points to the right places for things like dependency’s in /dep and plugin in /source

won't relative paths work? If their phpstan.neon only works in the poggit container, it can't be used anywhere else, then there will be a CI debug hell where you have to keep sending small commits just because you can't test your stuff beyond the CI environment.

**Comment by SOF3** [comment]
if they just want to customize the inspections, they could use phpstan.neon inheritance instead of using overwriting this one completely.

**Comment by JaxkDev** [comment]
> > > > Also should I just add a whole page for lint/phpstan there’s a bit to cover:
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > ```
> 
> > > > * Default Config.
> 
> > > > ```
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > ```
> 
> > > > * Default paths inside container (pmmp,dependancies).
> 
> > > > ```
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > ```
> 
> > > > * Composer support.
> 
> > > > ```
> 
> > > 
> 
> > > 
> 
> > > I don't think it is necessary to document default paths inside container. Why would we need to?
> 
> > 
> 
> > So they can setup a correct phpstan config that points to the right places for things like dependency’s in /dep and plugin in /source
> 
> 
> 
> won't relative paths work? If their phpstan.neon only works in the poggit container, it can't be used anywhere else, then there will be a CI debug hell where you have to keep sending small commits just because you can't test your stuff beyond the CI environment.

Relative would work but the paths are still in the root and set positions (/dep & /source & /pocketmine)

So even if they use relative paths it would mess their config if they’re not already using the pmmp-phpstan container for analysis

**Comment by JaxkDev** [comment]
> if they just want to customize the inspections, they could use phpstan.neon inheritance instead of using overwriting this one completely.

They should be able to

**Comment by SOF3** [comment]
> > > > > Also should I just add a whole page for lint/phpstan there’s a bit to cover:
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > * Default Config.
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > * Default paths inside container (pmmp,dependancies).
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > * Composer support.
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I don't think it is necessary to document default paths inside container. Why would we need to?
> > 
> > 
> > > 
> > 
> > 
> > > So they can setup a correct phpstan config that points to the right places for things like dependency’s in /dep and plugin in /source
> > 
> > 
> > won't relative paths work? If their phpstan.neon only works in the poggit container, it can't be used anywhere else, then there will be a CI debug hell where you have to keep sending small commits just because you can't test your stuff beyond the CI environment.
> 
> Relative would work but the paths are still in the root and set positions (/dep & /source & /pocketmine)
> 
> So even if they use relative paths it would mess their config if they’re not already using the pmmp-phpstan container for analysis

I mean why would they need to specify paths if they could use our base phpstan.neon file for the includes?

(trying hard to find a reason to further increase the blockquote levels)

**Comment by JaxkDev** [comment]
> > > > > > Also should I just add a whole page for lint/phpstan there’s a bit to cover:
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > * Default Config.
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > * Default paths inside container (pmmp,dependancies).
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > * Composer support.
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > I don't think it is necessary to document default paths inside container. Why would we need to?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > So they can setup a correct phpstan config that points to the right places for things like dependency’s in /dep and plugin in /source
> 
> > > 
> 
> > > 
> 
> > > won't relative paths work? If their phpstan.neon only works in the poggit container, it can't be used anywhere else, then there will be a CI debug hell where you have to keep sending small commits just because you can't test your stuff beyond the CI environment.
> 
> > 
> 
> > Relative would work but the paths are still in the root and set positions (/dep & /source & /pocketmine)
> 
> > 
> 
> > So even if they use relative paths it would mess their config if they’re not already using the pmmp-phpstan container for analysis
> 
> 
> 
> I mean why would they need to specify paths if they could use our base phpstan.neon file for the includes?
> 
> 
> 
> (trying hard to find a reason to further increase the blockquote levels)

They wouldn’t if they used the base config

**Comment by SOF3** [comment]
> > > > > > > Also should I just add a whole page for lint/phpstan there’s a bit to cover:
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > * Default Config.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > * Default paths inside container (pmmp,dependancies).
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > * Composer support.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > I don't think it is necessary to document default paths inside container. Why would we need to?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > So they can setup a correct phpstan config that points to the right places for things like dependency’s in /dep and plugin in /source
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > won't relative paths work? If their phpstan.neon only works in the poggit container, it can't be used anywhere else, then there will be a CI debug hell where you have to keep sending small commits just because you can't test your stuff beyond the CI environment.
> > 
> > 
> > > 
> > 
> > 
> > > Relative would work but the paths are still in the root and set positions (/dep & /source & /pocketmine)
> > 
> > 
> > > 
> > 
> > 
> > > So even if they use relative paths it would mess their config if they’re not already using the pmmp-phpstan container for analysis
> > 
> > 
> > I mean why would they need to specify paths if they could use our base phpstan.neon file for the includes?
> > (trying hard to find a reason to further increase the blockquote levels)
> 
> They wouldn’t if they used the base config

so it's probably not necessary to document paths; not even need to guarantee stability on the paths.

**Comment by JaxkDev** [comment]
This config is now final + tested.

**Pull request merged**
