### PR TITLE
Tasks and Concurrency: PluginTask is no longer necessary

### PR DESCRIPTION
**Pull request by GiantQuartz**
It doesn't even exist, TaskScheduler does all the dirty work now.

### CODE REVIEW

**Comment by SOF3** [comment]
PQRS is obsolete and is subject to removal.

**Comment by Thunder33345** [comment]
RIP

**Comment by dktapps** [comment]
> PQRS is obsolete and is subject to removal.

fix when ???

**Comment by SOF3** [comment]
https://github.com/poggit/support/blob/master/pqrs.md#L1

**Comment by dktapps** [comment]
@SOF3 people's eyes will immediately jump to the big text, perhaps wipe out the document apart from that notice?

**Pull request closed without merging**
